# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Synchron' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Synchron
  pod 'Firebase'
  pod 'AFNetworking', '~> 2.6.3'
  pod 'IQAudioRecorderController'
  pod 'MBProgressHUD'
  pod 'SDWebImage'
  pod 'JSQMessagesViewController'
  pod 'URBMediaFocusViewController'
  pod 'NZCircularImageView'

  target 'SynchronTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SynchronUITests' do
    inherit! :search_paths
    # Pods for testing
  end


end
